baseURL = "https://blog.jcatania.io/"
languageCode = "fr-fr"
title = "Blog JCatania.io"
copyright = "© {year}"
theme = "codex"
enableEmoji = true
googleAnalytics="UA-34338750-4"
[params]
  github = "https://github.com/Juu-"

# Controls the navigation
[[menu.main]]
identifier = "about"
name = "about"
title = "About"
url = "/"

[[menu.main]]
identifier = "blog"
name = "blog"
title = "Blog"
url = "/blog"
