baseURL = "https://blog.jcatania.io/"
languageCode = "fr-fr"
title = "Blog JCatania.io"
copyright = "© {year}"
theme = "codex"
enableEmoji = true
googleAnalytics="UA-34338750-4"
[params]
  github = "https://github.com/Juu-"
